name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: ./assets/github-contribution-grid-snake.svg
      - uses: actions/commit@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Update snake game"
