name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Bu satırı ekleyin!
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Generate Snake
      uses: Platane/snk@master  # @v3 yerine @master kullanın
      with:
        github_user_name: "betulyildizs"  # Kullanıcı adınızı manuel yazın
        outputs: |
          output/github-contribution-grid-snake.svg
          
    - name: Commit and Push
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add output/
        git commit -m "Update snake game"
        git push
